
##################
#  MQTT 配置
##################
mqtt:
  # 推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
  url: tcp://m2m.eclipse.org:1883
  ##################
  #  MQTT 生产者
  ##################
  # 连接服务器默认客户端ID
  producer:
    client-id: client
    # 用户名
    username: username
    # 密码
    password: password
  # 默认的推送主题，实际可在调用接口时指定
    default-topic: topic1

  ##################
  #  MQTT 消费者
  ##################
  # 连接服务器默认客户端ID
  consumer:
    # 默认的接收主题，可以订阅多个Topic，逗号分隔
    client-id: client
    # 用户名
    username: username
    # 密码
    password: password
    default-topic: topic1

