spring:
  redis:
    database: 10
    host: 192.168.1.25
    port: 17963
    timeout: PT10s
    password: qweqwe123
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        max-wait: PT10S
        min-idle: 1
  cache:
    type: redis
    redis:
      cache-null-values: false
